### ISSUE TITLE
Questions about the multi-variate kernel density estimation

### ISSUE THREAD

**Issue by songlin** [poetrywanderer/CF-NeRF#2]
Hello,  

Thanks for sharing the work. We are trying to follow your work in our paper. 
However, I am a little puzzled by the calculation here $\sigma_{rgb} *  (0.8/n)^{-1/7}$

The expression is corresponding to the following code.
https://github.com/poetrywanderer/CF-NeRF/blob/5e5a58304df1f1817c821466be4992e2cd29cde6/run_nerf_uncertainty_NF.py#L1036

Could you elaborate more?
Thank you.

Best,

**Comment by poetrywanderer** [comment]
Hi,

Thanks for your interest. Actually, the choice of bandwidth H is empirical. Here we follow **Silverman's rule of thumb**, H_sqrt = $\sigma_{rgb} * (\frac{4}{(d+2)*n})^{\frac{1}{d+4}}$. But we found -1/7 works better here. 

You can find more explanation here: https://en.wikipedia.org/wiki/Multivariate_kernel_density_estimation

Best,

**Comment by songlin** [comment]
I see. Thank you.

**Comment by songlin** [comment]
@poetrywanderer Hi, can you tell me how to acquire the `NLL` metric in Table. 1?
![微信图片_20230301172102](https://user-images.githubusercontent.com/853045/222096851-edc1299c-05b4-47c4-8003-934c289c2715.png)
Or if possible, just point me to the code for computing it. 
Thank you.

**Comment by csrqli** [comment]
> @poetrywanderer Hi, can you tell me how to acquire the `NLL` metric in Table. 1? ![微信图片_20230301172102](https://user-images.githubusercontent.com/853045/222096851-edc1299c-05b4-47c4-8003-934c289c2715.png) Or if possible, just point me to the code for computing it. Thank you.

Looking for the same thing tooo
