### ISSUE TITLE
"yml" not "yaml"

### ISSUE THREAD

**Issue by niki-amini-naieni** [poetrywanderer/CF-NeRF#6]
Hi,

Thanks for releasing the code! I believe the highlighted part of the Anaconda environment file should read "yml" not "yaml." 
<img width="630" alt="image" src="https://github.com/poetrywanderer/CF-NeRF/assets/61301874/fc362f5f-7983-4d6d-b0da-f7f20f6537b5">

**Comment by poetrywanderer** [comment]
Hi, 

Thanks for your reminder! We will correct it now.
